name: Creative Inc.
language: en
intro: |-
  I am a creative illustrator and graphic designer with more than 10 years of experience.

  Originally from Toronto, currently based in London.
copyright: "©2017 Your company - Made with DatoCMS"
social_profiles:
- url: https://www.facebook.com/xxx
  type: facebook
- url: https://twitter.com/xxx
  type: twitter
- url: https://instagram.com/xxx/
  type: instagram
- url: mailto:xxx@yyy.com
  type: email
favicon_meta_tags:
- tag_name: link
  attributes:
    sizes: 16x16
    type: image/png
    rel: icon
    href: https://www.datocms-assets.com/604/1479917977-Screenshot2016-11-2317.18.52.png?ch=DPR%2CWidth&auto=format&w=16&h=16
- tag_name: link
  attributes:
    sizes: 32x32
    type: image/png
    rel: icon
    href: https://www.datocms-assets.com/604/1479917977-Screenshot2016-11-2317.18.52.png?ch=DPR%2CWidth&auto=format&w=32&h=32
- tag_name: link
  attributes:
    sizes: 96x96
    type: image/png
    rel: icon
    href: https://www.datocms-assets.com/604/1479917977-Screenshot2016-11-2317.18.52.png?ch=DPR%2CWidth&auto=format&w=96&h=96
- tag_name: link
  attributes:
    sizes: 192x192
    type: image/png
    rel: icon
    href: https://www.datocms-assets.com/604/1479917977-Screenshot2016-11-2317.18.52.png?ch=DPR%2CWidth&auto=format&w=192&h=192
- tag_name: link
  attributes:
    sizes: 57x57
    rel: apple-touch-icon
    href: https://www.datocms-assets.com/604/1479917977-Screenshot2016-11-2317.18.52.png?ch=DPR%2CWidth&auto=format&w=57&h=57
- tag_name: link
  attributes:
    sizes: 60x60
    rel: apple-touch-icon
    href: https://www.datocms-assets.com/604/1479917977-Screenshot2016-11-2317.18.52.png?ch=DPR%2CWidth&auto=format&w=60&h=60
- tag_name: link
  attributes:
    sizes: 72x72
    rel: apple-touch-icon
    href: https://www.datocms-assets.com/604/1479917977-Screenshot2016-11-2317.18.52.png?ch=DPR%2CWidth&auto=format&w=72&h=72
- tag_name: link
  attributes:
    sizes: 76x76
    rel: apple-touch-icon
    href: https://www.datocms-assets.com/604/1479917977-Screenshot2016-11-2317.18.52.png?ch=DPR%2CWidth&auto=format&w=76&h=76
- tag_name: link
  attributes:
    sizes: 114x114
    rel: apple-touch-icon
    href: https://www.datocms-assets.com/604/1479917977-Screenshot2016-11-2317.18.52.png?ch=DPR%2CWidth&auto=format&w=114&h=114
- tag_name: link
  attributes:
    sizes: 120x120
    rel: apple-touch-icon
    href: https://www.datocms-assets.com/604/1479917977-Screenshot2016-11-2317.18.52.png?ch=DPR%2CWidth&auto=format&w=120&h=120
- tag_name: link
  attributes:
    sizes: 144x144
    rel: apple-touch-icon
    href: https://www.datocms-assets.com/604/1479917977-Screenshot2016-11-2317.18.52.png?ch=DPR%2CWidth&auto=format&w=144&h=144
- tag_name: link
  attributes:
    sizes: 152x152
    rel: apple-touch-icon
    href: https://www.datocms-assets.com/604/1479917977-Screenshot2016-11-2317.18.52.png?ch=DPR%2CWidth&auto=format&w=152&h=152
- tag_name: link
  attributes:
    sizes: 180x180
    rel: apple-touch-icon
    href: https://www.datocms-assets.com/604/1479917977-Screenshot2016-11-2317.18.52.png?ch=DPR%2CWidth&auto=format&w=180&h=180
- tag_name: meta
  attributes:
    name: msapplication-square70x70logo
    content: https://www.datocms-assets.com/604/1479917977-Screenshot2016-11-2317.18.52.png?ch=DPR%2CWidth&auto=format&w=70&h=70
- tag_name: meta
  attributes:
    name: msapplication-square150x150logo
    content: https://www.datocms-assets.com/604/1479917977-Screenshot2016-11-2317.18.52.png?ch=DPR%2CWidth&auto=format&w=150&h=150
- tag_name: meta
  attributes:
    name: msapplication-square310x310logo
    content: https://www.datocms-assets.com/604/1479917977-Screenshot2016-11-2317.18.52.png?ch=DPR%2CWidth&auto=format&w=310&h=310
- tag_name: meta
  attributes:
    name: msapplication-square310x150logo
    content: https://www.datocms-assets.com/604/1479917977-Screenshot2016-11-2317.18.52.png?ch=DPR%2CWidth&auto=format&w=310&h=150
- tag_name: meta
  attributes:
    name: application-name
    content: DatoCMS demo